sudo: required

language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - pip install docker-compose
  - docker-compose -v

before_script:
  - pip install flake8
  - flake8 -v .
  - python setup.py sdist install

script:
  - docker-compose -f docker/docker-compose.yml up --build
  - docker-compose -f docker/docker-compose.yml stop
  - docker-compose -f docker/docker-compose.yml rm -fv
